services:
  postgres:
    image: postgres:17
    container_name: hpb_tct_postgres
    environment:
      POSTGRES_DB: first_db_local
      POSTGRES_USER: bulldog
      POSTGRES_PASSWORD: Schlittlebah44!
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: hpb_tct_redis
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
