services:
  postgres:
    image: postgres:17
    container_name: hpb_tct_postgres
    env_file:
      - .env.local
    environment:
      POSTGRES_DB: ${BACKTEST_DB_NAME}
      POSTGRES_USER: ${BACKTEST_DB_USER}
      POSTGRES_PASSWORD: ${BACKTEST_DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: hpb_tct_redis
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
